"""Add user data

Revision ID: 253dcf3f1829
Revises: a27231b3b243
Create Date: 2020-11-13 22:37:29.997782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253dcf3f1829'
down_revision = 'a27231b3b243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('surname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
