"""Add breed column

Revision ID: 799431d75ed0
Revises: 
Create Date: 2020-11-11 23:21:29.628777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799431d75ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
